# Nombre del action
name: Tests automáticos

# En qué eventos y ramas se activa
on:
  push:
    branches: [ "jcapitan-2" ]

# Tareas
jobs:
  test: # Tarea "build"
    permissions: write-all # Tiene permiso para escribir
    runs-on: ubuntu-latest # Sistema operativo en el que se ejecuta el action

    steps: # Pasos
      - uses: actions/checkout@v4 # Hace un checkout del código
      # Configura Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Acción que configura el JDK
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Verifica con Maven
        run: mvn --batch-mode --update-snapshots verify --file pom.xml # Comando para testear el código con maven

      # Genera un informe
      - name: Report
        uses: dorny/test-reporter@v1 # Acción que genera el informe
        if: always() # Ejecutar siempre, aunque lo anterior falle.
        with:
          name: Informe de tests
          path: target/surefire-reports/*.xml # Ruta para guardar los informes
          reporter: java-junit
          fail-on-error: true # Si hay error marcar como tarea fallida.

  publish:
    needs: test # Indica que necesita que la tarea test se ejecute con éxito
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4 # Hace checkout del código
      - uses: actions/setup-java@v4 # Configura el SDK
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publicar paquete
        run: mvn --batch-mode deploy # Publica el paquete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
